instance_type: t2.micro
instance_name: terrafor_dev
terraform_sec: terraform_sec
instruqt_tf_build: myTest5
working_dir: /tmp/srv/
templates_dir: /tmp/template
survey_j2: survey_spec.json.j2
survey_file: remove_vm_survey.json
student_user: student
student_password: learn_ansible