# Gitea config
- name: Configure Gitea host
  hosts: gitea
  gather_facts: false
  become: true
  tags:
    - gitea-config

  tasks:
    - name: Install python3 Gitea
      ansible.builtin.raw: /sbin/apk add python3

    - name: Install Gitea packages
      community.general.apk:
        name: subversion, tar
        state: present

    - name: Create repo users
      ansible.builtin.command: "{{ item }}"
      become_user: git
      register: __output
      failed_when: __output.rc not in [ 0, 1 ]
      changed_when: '"user already exists" not in __output.stdout'
      loop:
        - "/usr/local/bin/gitea admin user create --admin --username {{ student_user }} --password {{ student_password }} --must-change-password=false --email {{ student_user }}@localhost"

    - name: Create repo for terraform builds
      ansible.builtin.uri:
        url: http://gitea:3000/api/v1/user/repos
        method: POST
        body_format: json
        body:
          name: terraform_builds
          auto_init: false
          private: false
        force_basic_auth: true
        url_password: "{{ student_password }}"
        url_username: "{{ student_user }}"
        status_code: [201, 409]

    - name: Create repo for project 
      ansible.builtin.uri:
        url: http://gitea:3000/api/v1/user/repos
        method: POST
        body_format: json
        body:
          name: terraform_prov
          auto_init: false
          private: false
        force_basic_auth: true
        url_password: "{{ student_password }}"
        url_username: "{{ student_user }}"
        status_code: [201, 409]

    - name: Configre lab content
      block:

        - name: update build repo
          ansible.builtin.shell:
            shell: git config --global user.name "Student" && git config --global user.email "student@acme.corp"

        - name: Clone public content
          repo: https://github.com/nmartins0611/instruqt_labs.git
          dest: /tmp/
          clone: yes

        - name: Clone gitea build repo
          ansible.builtin.git:
           repo: http://gitea:3000/student/terraform_builds.git
           dest: /tmp/
           clone: yes

        - name: Clone gitea provision repo
          ansible.builtin.git:
           repo: http://gitea:3000/student/terraform_prov.git
           dest: /tmp/
           clone: yes

        - name: Update repo for builds
          ansible.builtin.copy:
           src: /tmp/instruqt_labs/build_repo/
           dest: /tmp/terraform_builds/

        - name: Update Terraform build repo
          ignore_errors: true 
          ansible.builtin.shell: git add * && git commit -m "Building Terraform Lab Files" && git push
            args:
              chdir: /tmp/terraform_builds/ 

        - name: Update repo for AAP
          ansible.builtin.copy:
           src: /tmp/instruqt_labs/prov_repo/
           dest: /tmp/terraform_prov/

        - name: Update Terraform build repo
          ignore_errors: true 
          ansible.builtin.shell: git add * && git commit -m "Building Terraform Lab Files" && git push
            args:
              chdir: /tmp/terraform_prov/


    